package io.platform.ephemeral;

import io.platform.api.v1alpha1.EphemeralSpec;
import io.platform.api.v1alpha1.ResilienceSpec;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Merges five layers of configuration into a single {@code application.properties}
 * content string for ephemeral worker pods.
 *
 * <pre>
 * Layer 1 — Worker image built-in (baked into the image; not modified here)
 * Layer 2 — Component-required properties (auto-detected from route YAML)
 * Layer 3 — Scaffold-generated (OTel, resilience from spec.resilience)
 * Layer 4 — User explicit overrides (spec.ephemeral.properties)
 * Layer 5 — Disable filter (spec.ephemeral.disableProperties glob removal)
 * </pre>
 */
@ApplicationScoped
public class EphemeralConfigMerger {

    @Inject
    ComponentPropertiesRegistry componentRegistry;

    /**
     * Produces the merged {@code application.properties} content.
     *
     * @param detectedComponents Camel component schemes found in the route
     * @param scaffoldProperties properties generated by the scaffolding service (OTel, resilience)
     * @param ephemeralSpec      user's ephemeral config from the CR (nullable)
     * @param resilience         spec.resilience from the CR (nullable)
     * @return properties file content ready to mount in the worker ConfigMap
     */
    public String merge(Set<String> detectedComponents, String scaffoldProperties,
                        EphemeralSpec ephemeralSpec, ResilienceSpec resilience) {

        Map<String, String> merged = new LinkedHashMap<>();

        // Layer 2: component-required properties
        merged.putAll(componentRegistry.resolveFor(detectedComponents));

        // Layer 3: scaffold-generated (OTel, resilience, app name)
        if (scaffoldProperties != null) {
            parseProperties(scaffoldProperties, merged);
        }

        // Layer 4: user explicit overrides from CR
        if (ephemeralSpec != null && ephemeralSpec.getProperties() != null) {
            merged.putAll(ephemeralSpec.getProperties());
        }

        // Layer 5: disable filter — remove matching keys
        if (ephemeralSpec != null && ephemeralSpec.getDisableProperties() != null) {
            applyDisableFilter(merged, ephemeralSpec.getDisableProperties());
        }

        return formatProperties(merged);
    }

    private void parseProperties(String propsContent, Map<String, String> target) {
        for (String line : propsContent.split("\n")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;
            int eq = trimmed.indexOf('=');
            if (eq > 0) {
                target.put(trimmed.substring(0, eq).trim(), trimmed.substring(eq + 1).trim());
            }
        }
    }

    private void applyDisableFilter(Map<String, String> props, List<String> patterns) {
        for (String globPattern : patterns) {
            Pattern regex = globToRegex(globPattern);
            Iterator<String> keys = props.keySet().iterator();
            while (keys.hasNext()) {
                if (regex.matcher(keys.next()).matches()) {
                    keys.remove();
                }
            }
        }
    }

    static Pattern globToRegex(String glob) {
        StringBuilder sb = new StringBuilder("^");
        for (char c : glob.toCharArray()) {
            switch (c) {
                case '*' -> sb.append(".*");
                case '?' -> sb.append('.');
                case '.' -> sb.append("\\.");
                default -> sb.append(c);
            }
        }
        sb.append('$');
        return Pattern.compile(sb.toString());
    }

    private String formatProperties(Map<String, String> props) {
        if (props.isEmpty()) return "";
        var sb = new StringBuilder();
        for (var entry : props.entrySet()) {
            sb.append(entry.getKey()).append('=').append(entry.getValue()).append('\n');
        }
        return sb.toString();
    }
}
