quarkus.application.name=integration-flow
quarkus.opentelemetry.enabled=true
quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://otel-collector:4317
quarkus.log.level=INFO
quarkus.http.port=8080
