{{- if .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: integration-git-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.externalSecrets.gitCredentialsSecretName | default "integration-git-credentials" }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: integration-platform/git
        property: username
    - secretKey: password
      remoteRef:
        key: integration-platform/git
        property: password
    - secretKey: github-token
      remoteRef:
        key: integration-platform/github
        property: token
    - secretKey: gitlab-token
      remoteRef:
        key: integration-platform/gitlab
        property: token
{{- end }}
