{{- if eq .Values.secrets.provider "values" }}
{{- $username := .Values.git.username | default .Values.gitea.username | default "" }}
{{- $password := .Values.git.password | default .Values.gitea.password | default "" }}
{{- $gitBaseUrl := .Values.git.url | default .Values.gitea.url | default "" }}
{{- $gitHost := regexReplaceAll "^https?://" $gitBaseUrl "" | trimSuffix "/" }}
{{- if and $username $password $gitHost }}
apiVersion: v1
kind: Secret
metadata:
  name: integration-git-basic-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    platform.io/component: build
type: Opaque
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
  .git-credentials: {{ printf "https://%s:%s@%s" $username $password $gitHost | quote }}
  .gitconfig: |
    [safe]
      directory = *
    [credential]
      helper = store
{{- end }}
{{- end }}
