{{- $username := .Values.git.username | default .Values.gitea.username | default "" }}
{{- $password := .Values.git.password | default .Values.gitea.password | default "" }}
{{- if and $username $password }}
apiVersion: v1
kind: Secret
metadata:
  name: integration-git-basic-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    platform.io/component: build
type: Opaque
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
{{- end }}
