apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
