apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "operator.fullname" . }}-serving-cert
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.operator.proxyPort | default 8443 }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
