server {
    listen 9443 ssl;
    ssl_certificate /var/serving-cert/tls.crt;
    ssl_certificate_key /var/serving-cert/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /opt/app-root/src;
    index plugin-manifest.json;

    location / {
        try_files $uri $uri/ /plugin-manifest.json;
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin "*";
    }

    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
